#applicationName: CWDS API FUNCTIONAL TESTING

tokenCredentials:
   baseUrl: ${BASE_URL}
   perryLoginUrl: ${PERRY_LOGIN_URL}
   authLoginUrl: ${AUTH_LOGIN_URL}
   tokenUrl: ${TOKEN_URL}
   callBackUrl: ${CALL_BACK_URL}
   logOutUrl: ${LOG_OUT_URL}
   authenticationMode: TEST
   
socialWorkerOnly:
   username:  
   password: 
   
countySensitivePrivilegeUser:
   username: 
   password:   
   
countySealedPrivilegeUser:
   username:
   password:

stateSensitivePrivilegeUser:
   username:  
   password: 
   
stateSealedPrivilegeUser:
   username:  
   password:      
      