#applicationName: CWDS API FUNCTIONAL TESTING

tokenCredentials:
   baseUrl: https://sectest.dss.ca.gov
   perryLoginUrl: https://web.preint.cwds.io/perry/login
   authLoginUrl: https://web.preint.cwds.io/perry/authn/login
   tokenUrl: https://web.preint.cwds.io/perry/authn/token
   callBackUrl: https://ferbapi.preint.cwds.io/swagger
   logOutUrl: https://web.preint.cwds.io/perry/authn/logout
   authenticationMode: TEST
   
socialWorkerOnly:
   username:  
   password: 
   
countySensitivePrivilegeUser:
   username: 
   password:   
   
countySealedPrivilegeUser:
   username:
   password:

stateSensitivePrivilegeUser:
   username:  
   password: 
   
stateSealedPrivilegeUser:
   username:  
   password:      
      