#applicationName: CWDS API FUNCTIONAL TESTING

tokenCredentials:
   baseUrl: Adarsh
   perryLoginUrl: ${PERRY_LOGIN_URL:-}
   authLoginUrl: ${AUTH_LOGIN_URL:-}
   tokenUrl: ${TOKEN_URL:-}
   callBackUrl: ${CALL_BACK_URL:-}
   logOutUrl: ${LOG_OUT_URL:-}
   authenticationMode: TEST       