#applicationName: CWDS API FUNCTIONAL TESTING
#If you are creating your own yaml file in your project please follow the same naming pattern. 

authenticationMode: TEST
testUrl:
   baseUrl: ${BASE_URL:-https://ferbapi.preint.cwds.io}
   authenticationBaseUrl: ${BASE_URL:-https://localhost:8070}
   perryLoginUrl: ${PERRY_LOGIN_URL:-https://localhost:8090/perry/login}
   authLoginUrl: ${AUTH_LOGIN_URL:-https://localhost:8090/perry/authn/login}
   tokenUrl: ${TOKEN_URL:-https://localhost:8090/perry/authn/token}
   callBackUrl: ${CALL_BACK_URL:-https://ferbapi.preint.cwds.io/swagger}
   logOutUrl: ${LOG_OUT_URL:-}
   
defaultUsers:
    -  userType: socialWorkerOnly
       username: ${USERNAME:-}
       password: ${PASSWORD:-}
       
    -  userType: countySensitivePrivilegeUser
       username: ${USERNAME:-}
       password: ${PASSWORD:-}  
        
